{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ngrinder",
    "module": "ngrinder-groovy",
    "version": "3.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "brwhaxwsynhj3psvwnsuyn6wji"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ngrinder",
          "module": "ngrinder-runtime",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "2.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ngrinder-groovy-3.5.0.jar",
          "url": "ngrinder-groovy-3.5.0.jar",
          "size": 43144,
          "sha512": "9cbb06bf8caf0c512d459aea1e2c7d8123953bbb27dc4042b3f29fc88ca2448306d85564d3f26a5c6044b898bb6e5f14dbca41c6246295a2b0d5d2ddc0f61180",
          "sha256": "17245d5e9fa9a8a56acb47c16f36e1d00fa5b472c82f327d0cd9de608f12aad9",
          "sha1": "4a499ec46d5534435b28efe989a60917e034f5e5",
          "md5": "926fe4d67758610ded9d91d9abaa3040"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ngrinder",
          "module": "ngrinder-runtime",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "2.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ngrinder-groovy-3.5.0.jar",
          "url": "ngrinder-groovy-3.5.0.jar",
          "size": 43144,
          "sha512": "9cbb06bf8caf0c512d459aea1e2c7d8123953bbb27dc4042b3f29fc88ca2448306d85564d3f26a5c6044b898bb6e5f14dbca41c6246295a2b0d5d2ddc0f61180",
          "sha256": "17245d5e9fa9a8a56acb47c16f36e1d00fa5b472c82f327d0cd9de608f12aad9",
          "sha1": "4a499ec46d5534435b28efe989a60917e034f5e5",
          "md5": "926fe4d67758610ded9d91d9abaa3040"
        }
      ]
    }
  ]
}
