{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ngrinder",
    "module": "ngrinder-core",
    "version": "3.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "r4elnsknazhkvnqtx553el6ejy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ngrinder",
          "module": "ngrinder-runtime",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.ngrinder",
          "module": "ngrinder-groovy",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.fusesource",
          "module": "sigar",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.pf4j",
          "module": "pf4j",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "javax.servlet",
          "module": "javax.servlet-api",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "commons-collections",
          "module": "commons-collections",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.python",
          "module": "jython-standalone",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.9.9"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.9.9"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "com.beust",
          "module": "jcommander",
          "version": {
            "requires": "1.32"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.28"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.28"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.3.11.Final"
          }
        },
        {
          "group": "org.jboss.spec.javax.transaction",
          "module": "jboss-transaction-api_1.2_spec",
          "version": {
            "requires": "1.0.1.Final"
          }
        }
      ],
      "files": [
        {
          "name": "ngrinder-core-3.5.0.jar",
          "url": "ngrinder-core-3.5.0.jar",
          "size": 711165,
          "sha512": "bd0f578ff8d88f3fd11724fc58102eddccd766293495c49bf5bc5e94ff76aba110778681a191675625a34700b9bc22e177c3f3f78145e0300cdbe5c07374ccd5",
          "sha256": "25cc92a84616ec84d663b48b6bdf6f811e00f005f91f19e223c620b93343570a",
          "sha1": "0729f24bee3784251d4d3147173f56bf0d3c0ce2",
          "md5": "f07778301d818dec37565379a887ae1a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ngrinder",
          "module": "ngrinder-runtime",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.ngrinder",
          "module": "ngrinder-groovy",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.fusesource",
          "module": "sigar",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.pf4j",
          "module": "pf4j",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "javax.servlet",
          "module": "javax.servlet-api",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "commons-collections",
          "module": "commons-collections",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.python",
          "module": "jython-standalone",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.9.9"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.9.9"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "com.beust",
          "module": "jcommander",
          "version": {
            "requires": "1.32"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.28"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.28"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.3.11.Final"
          }
        },
        {
          "group": "org.jboss.spec.javax.transaction",
          "module": "jboss-transaction-api_1.2_spec",
          "version": {
            "requires": "1.0.1.Final"
          }
        }
      ],
      "files": [
        {
          "name": "ngrinder-core-3.5.0.jar",
          "url": "ngrinder-core-3.5.0.jar",
          "size": 711165,
          "sha512": "bd0f578ff8d88f3fd11724fc58102eddccd766293495c49bf5bc5e94ff76aba110778681a191675625a34700b9bc22e177c3f3f78145e0300cdbe5c07374ccd5",
          "sha256": "25cc92a84616ec84d663b48b6bdf6f811e00f005f91f19e223c620b93343570a",
          "sha1": "0729f24bee3784251d4d3147173f56bf0d3c0ce2",
          "md5": "f07778301d818dec37565379a887ae1a"
        }
      ]
    }
  ]
}
